
name: sejamdependencies
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip

  - pip:
      - onnxruntime
      - azureml-core
      - azureml-defaults
      - nltk
      - numpy



      
